name: sync_to_gitlab

on:
  pull_request:
  push:
  workflow_dispatch:

concurrency:
  group: ${{github.workflow}}

jobs:
  compile:
    runs-on: ubuntu-latest

    steps:
      - uses: keninkujovic/gitlab-sync@2.0.0
        with:
          gitlab_url: https://gitlab.com/novi028/JS-Slash-Runner.git
          username: novi028
          gitlab_pat: ${{ secrets.GITLAB_PAT }}
