name: webpack

on:
  pull_request:
  push:
  workflow_dispatch:

concurrency:
  group: ${{github.workflow}}

jobs:
  compile:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          repository: SillyTavern/SillyTavern
          ref: staging
      - uses: actions/checkout@v4
        with:
          path: public/scripts/extensions/third-party/JS-Slash-Runner
          ssh-key: ${{ secrets.RSA_PRIVATE_KEY }}
      - name: Use Node.js
        uses: actions/setup-node@v4
        with: { node-version: 22 }
      - name: Setup pnpm
        uses: pnpm/action-setup@v4.1.0
        with: { version: 10 }
      - run: pnpm i
        working-directory: public/scripts/extensions/third-party/JS-Slash-Runner
      - run: pnpm build
        working-directory: public/scripts/extensions/third-party/JS-Slash-Runner
      - name: Commit changes
        uses: EndBug/add-and-commit@v9.1.3
        with:
          default_author: github_actions
          message: '[bot] Webpack'
          cwd: public/scripts/extensions/third-party/JS-Slash-Runner
